import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import MobileShell from '@/components/MobileShell';
import { base44 } from '@/api/base44Client';
import { getSession, saveSession } from '@/lib/onboardingState';

export default function Processing() {
  const navigate=useNavigate(),[error,setError]=useState(''),[attempt,setAttempt]=useState(0);
  useEffect(()=>{const run=async()=>{setError('');const s=getSession()||{};try{
    const result=await base44.integrations.Core.InvokeLLM({prompt:`Create exactly two realistic income paths this person can start. Be specific to location, assets, time, and urgency. Avoid hype and generic ideas. Profile: ${JSON.stringify({location:s.location,situation:s.situation,timeline:s.timeline,hours:s.hours_per_week,assets:s.selected_assets,extra:s.extra_skills_text})}. Each action step needs task, estimated_minutes, and 2-3 concrete tips.`,response_json_schema:{type:'object',properties:{option1:{type:'object',properties:{title:{type:'string'},emoji:{type:'string'},income_range:{type:'string'},time_to_first_dollar:{type:'string'},why_this_fits_you:{type:'string'},milestones:{type:'array',items:{type:'object'}},action_steps:{type:'array',items:{type:'object'}}},required:['title','income_range','why_this_fits_you','action_steps']},option2:{type:'object',properties:{title:{type:'string'},emoji:{type:'string'},income_range:{type:'string'},time_to_first_dollar:{type:'string'},why_this_fits_you:{type:'string'},milestones:{type:'array',items:{type:'object'}},action_steps:{type:'array',items:{type:'object'}}},required:['title','income_range','why_this_fits_you','action_steps']}},required:['option1','option2']}});
    const user=await base44.auth.me();const existing=await base44.entities.UserProfile.filter({created_by_id:user.id});const data={...s,option1:result.option1,option2:result.option2,first_goal_amount:100,money_earned:0,is_paid:existing[0]?.is_paid||false};const profile=existing[0]?await base44.entities.UserProfile.update(existing[0].id,data):await base44.entities.UserProfile.create(data);saveSession({...data,profile_id:profile.id});navigate('/results');
  }catch(e){setError(e.message||'We could not build your plan.');}};run()},[attempt]);
  return <MobileShell><div className="min-h-[680px] flex flex-col items-center justify-center p-8 text-center bg-[#183b3b] text-white"><div className="text-6xl">⚡</div><h1 className="text-2xl font-black mt-6">Finding your fastest path...</h1><p className="text-white/60 mt-3">Matching what you have with what can earn first.</p>{error&&<div className="mt-8"><p className="text-red-200 text-sm">{error}</p><button onClick={()=>setAttempt(x=>x+1)} className="mt-4 bg-[#5BC8C8] px-6 py-3 rounded-full font-bold">Try again</button></div>}</div></MobileShell>;
}